basemodel: "daml"
data:
  use_review_text: true
  use_review_embedding: false
  use_sentiment: false
  glove_path: "/home/infolab/mnt/mingyu/review_rec/cached/others/GoogleNews-vectors-negative300.txt"
  drop_cold_start_eval: false
model:
  doc_len: 200
  word_dim: 100
  filters_num: 50
  kernel_size: 3
  id_emb_size: 8
  dropout_prob: 0.2
  l2_reg_lambda: 0.0
  freeze_word_embedding: true
  attention_chunk_size: 64
training:
  batch: 8
  eval_batch: 16
  epoch: 20
  lr: 0.0001
  lr_decay: 1.0
  weight_decay: 0.001
evaluation:
  best_metric_name: "mae"
  early_stop_patience: 10
  eval_clip: false
  min_rating: 1.0
  max_rating: 5.0
