basemodel: "deepconn"
data:
  use_review_text: true
  use_review_embedding: false
  use_sentiment: false
  glove_path: "/home/infolab/mnt/mingyu/review_rec/cached/others/glove.6B.50d.txt"
model:
  review_count: 10
  review_length: 40
  word_dim: 50
  kernel_count: 100
  kernel_size: 3
  cnn_out_dim: 50
  fm_k: 10
  dropout_prob: 0.5
  retain_rui: false
training:
  batch: 128
  epoch: 200
  lr: 0.001
  lr_decay: 0.95
  weight_decay: 1.0e-2
evaluation:
  min_rating: 1.0
  max_rating: 5.0
