basemodel: "ssg"
glove_path: "/home/infolab/mnt/mingyu/review_rec/cached/others/GoogleNews-vectors-negative300.txt"
batch: 32
epoch: 100
lr: 0.001
review_count: 10
review_length: 40
seq_count: 10
word_dim: 300
filter_sizes: [3]
num_filters: 100
id_dim: 32
attention_size: 32
gru_dim: 100
time_dim: 32
latent_dim: 32
use_set_view: true
use_sequence_view: true
use_graph_view: false
graph_hidden_dim: 32
graph_node_dim: 32
graph_attention_dim: 32
n_hops: 2
n_heads: 2
alpha: 0.2
dropout_prob: 0.5
decov_lambda: 0.01
l2_lambda: 0.001
retain_rui: false
lr_decay: 0.95
min_rating: 1.0
max_rating: 5.0
weight_decay: 0.0
